################## 系统配置 ##################

search:
  includes:
    - post
    - page

################## 样式配置 ##################

# 图片配置
image:
  favicon: /myblog.github.io/assets/manbo.png # 站点图标
  avatar: /myblog.github.io/images/IMG_5529.GIF # 个人信息挂件上的头像
  banner:
    light: /myblog.github.io/images/ban.png
    dark: /myblog.github.io/images/ban-dark.png
  background:
    light: /myblog.github.io/images/background-sun.png
    dark: /myblog.github.io/images/background.png

# 顶部导航栏配置
nav:
  items:
    - label: Home
      icon: home
      url: /
    - label: Archives
      icon: archive
      url: /archives/
    - label: Links
      icon: link
      submenu:
        - label: 代码仓库
          icon: code
          url: https://github.com/Candinya/Kratos-Rebirth
        - label: 项目文档
          icon: book
          url: https://wiki.krt.moe
    - label: Funry
      icon: gamepad
      submenu:
        - label: "2048"
          icon: trophy
          url: /game/2048/index.html
        - label: Ball
          icon: futbol-o 
          url: /game/ball/index.html
        - label: Maze
          icon: map-marker
          url: /game/maze/index.html

# Footer 页脚配置
footer:
  links:
    - icon: github
      link: https://github.com/Hyperion1230
    - icon: rss
      link: /myblog.github.io/atom.xml
  components:
    uptime:
      since: "2025/09/18 13:03:12"
      text: "本站已运行"
    author:
      homepage: "https://github.com/Hyperion1230/myblog.github.io/"
    additional: # 托管信息等
      - - 由 <a href="https://hexo.io" target="_blank" rel="nofollow">Hexo</a> 部署
        -  <a href="https://github.io" target="_blank">Github Pages</a> 托管

# 代码高亮
# syntax_highlighter:
  #theme: atom-dark # 代码高亮主题（请参照具体的高亮插件对应的主题样式）

# Widgets 侧边栏小挂件
sidebar:
  widgets:
    - about
    - splitter
    - toc
    - category
    - tagcloud
    - posts

# 分享组件设置
share:
  enable: true
  title: "Share this moment！"
  message: "好东西要和大家分享！"
  platforms:  
    - name: "喵窝"
      icon: <svg fill="currentColor" width="18" height="18" viewBox="0 0 329 388"><path d="M0,36.226c0,-19.993 16.233,-36.226 36.226,-36.226c13.788,0 25.787,7.719 31.908,19.068l188.366,229.845l0,-111.259c-6.356,5.508 -14.645,8.843 -23.707,8.843c-19.994,0 -36.226,-16.232 -36.226,-36.226c-0,-8.551 2.968,-16.413 7.93,-22.613l-0.015,-0.013l56.614,-69.08c6.2,-11.073 18.047,-18.565 31.63,-18.565c19.994,0 36.227,16.233 36.227,36.226l-0,314.644c-0,19.994 -16.233,36.226 -36.227,36.226c-13.166,0 -24.701,-7.039 -31.044,-17.555l-189.229,-230.899l-0,212.228c-0,19.994 -16.233,36.226 -36.227,36.226c-19.993,0 -36.226,-16.232 -36.226,-36.226l0,-314.644Z" /></svg>
      color: "#62b6e7"
      link: "https://nya.one/share?text=%3E%20$TITLE%0A%3E%0A%3E%20$SUMMARY%0A----%20$SITE%0A%0A$URL"
    - name: "QQ"
      icon: "<i class=\"fa fa-qq\"></i>"  # 使用Font Awesome图标
      color: "#12B7F5"
      link: "https://connect.qq.com/widget/shareqq/index.html?url=$URL&title=$TITLE&desc=&summary=$SUMMARY&site=$SITE"
    - name: "微信"
      icon: "<i class=\"fa fa-weixin\"></i>"  # 使用Font Awesome图标
      color: "#07c160"
      link: "https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=$URL"
# 打赏组件设置
donate:
  enable: true
  title: "赞助喵"
  message: 非常感谢您的喜欢！ <i class="fa fa-heart" style="color:#d43f57"></i>
  qrcode_placeholder: "https://dev.krt.moe/demo-assets/donate.webp"
  platforms:
    - name: "模拟支付"
      icon: "credit-card"
      color: "skyblue"
      qrcode: "example_payment"

# 版权说明
# copyright_notice:
#   in_page:
#     enable_at:
#       - post
#       - page

#pjax设置
pjax: true


# 评论系统
comments:
  core:
    enable_at:
    # - index
      - post
      - page
    template:
      _shared: <div id="gitalk-container" class="kr-comments lazy-load" data-path="$PATH" data-path-hash="$PATH_HASH"></div>
      index: ""
      post: ""
      page: ""
  count:
    enable_at: []
    # - index
    # - post
    template:
      _shared: ""
      index: ""
      post: ""

# 访问数量统计
visit_count:
  enable_at: []
  template:
    _shared: ""
    index: ""
    post: ""

posts:
  default_cover: /myblog.github.io/images/default.png # 没有头图的文章使用的默认图片
  donate: false # 默认是否启用打赏功能
  share: true # 默认是否启用分享功能
  word_count: # 字数统计功能
    enable: true # 是否启用
    threshold: 1500 # 超过多少字开始显示为千字
    estimate_wavy: true # 在千字的约数前显示波浪号
  toc: # 文章目录
    desktop: # 桌面端
      list_number: false # 显示数字标号
    mobile: # 移动端
      enable: true # 是否启用
      list_number: true # 显示数字标号

################## 额外的注入代码 ##################
additional_injections:
  head: |
    <link rel="stylesheet" href="/myblog.github.io/css/custom.css">
    <link rel="stylesheet" href="/myblog.github.io/music/APlayer.min.css">
    <link rel="stylesheet" href="https://unpkg.com/gitalk/dist/gitalk.css">
    <link rel="stylesheet" href="/myblog.github.io/comments/gitalk.css" />
    <link rel="stylesheet" href="/myblog.github.io/music/aplayer.css">
  footer: |
    <script>
    (function() {
      var hour = new Date().getHours();
          var isDark = hour >= 18 || hour < 6;
            if (isDark) {
              document.documentElement.setAttribute('data-theme', 'dark');
          } else {
              document.documentElement.setAttribute('data-theme', 'light');
                        }
                        })();
                        </script>
    <meting-js server="netease" type="playlist" id="12511958644" fixed="true" order="random"></meting-js>
                            
  after_footer: |
   <script src="https://unpkg.com/gitalk/dist/gitalk.min.js"></script>
   <script src="/myblog.github.io/comments/gitalk.js"></script>
   <script src="/myblog.github.io/music/APlayer.min.js"></script>
   <script src="/myblog.github.io/music/Meting.min.js"></script>